# CMake generated Testfile for 
# Source directory: C:/dev/igrep/packages/libarchive-2.8.4/cpio/test
# Build directory: C:/dev/igrep/packages/libarchive-2.8.4/cpio/test
# 
# This file includes the relevent testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(bsdcpio_test_0 "C:/dev/igrep/packages/libarchive-2.8.4/bin/bsdcpio_test.exe" "-vv" "-p" "C:/dev/igrep/packages/libarchive-2.8.4/bin/bsdcpio.exe" "-r" "C:/dev/igrep/packages/libarchive-2.8.4/cpio/test" "test_0")
ADD_TEST(bsdcpio_test_basic "C:/dev/igrep/packages/libarchive-2.8.4/bin/bsdcpio_test.exe" "-vv" "-p" "C:/dev/igrep/packages/libarchive-2.8.4/bin/bsdcpio.exe" "-r" "C:/dev/igrep/packages/libarchive-2.8.4/cpio/test" "test_basic")
ADD_TEST(bsdcpio_test_cmdline "C:/dev/igrep/packages/libarchive-2.8.4/bin/bsdcpio_test.exe" "-vv" "-p" "C:/dev/igrep/packages/libarchive-2.8.4/bin/bsdcpio.exe" "-r" "C:/dev/igrep/packages/libarchive-2.8.4/cpio/test" "test_cmdline")
ADD_TEST(bsdcpio_test_format_newc "C:/dev/igrep/packages/libarchive-2.8.4/bin/bsdcpio_test.exe" "-vv" "-p" "C:/dev/igrep/packages/libarchive-2.8.4/bin/bsdcpio.exe" "-r" "C:/dev/igrep/packages/libarchive-2.8.4/cpio/test" "test_format_newc")
ADD_TEST(bsdcpio_test_gcpio_compat "C:/dev/igrep/packages/libarchive-2.8.4/bin/bsdcpio_test.exe" "-vv" "-p" "C:/dev/igrep/packages/libarchive-2.8.4/bin/bsdcpio.exe" "-r" "C:/dev/igrep/packages/libarchive-2.8.4/cpio/test" "test_gcpio_compat")
ADD_TEST(bsdcpio_test_option_B_upper "C:/dev/igrep/packages/libarchive-2.8.4/bin/bsdcpio_test.exe" "-vv" "-p" "C:/dev/igrep/packages/libarchive-2.8.4/bin/bsdcpio.exe" "-r" "C:/dev/igrep/packages/libarchive-2.8.4/cpio/test" "test_option_B_upper")
ADD_TEST(bsdcpio_test_option_C_upper "C:/dev/igrep/packages/libarchive-2.8.4/bin/bsdcpio_test.exe" "-vv" "-p" "C:/dev/igrep/packages/libarchive-2.8.4/bin/bsdcpio.exe" "-r" "C:/dev/igrep/packages/libarchive-2.8.4/cpio/test" "test_option_C_upper")
ADD_TEST(bsdcpio_test_option_J_upper "C:/dev/igrep/packages/libarchive-2.8.4/bin/bsdcpio_test.exe" "-vv" "-p" "C:/dev/igrep/packages/libarchive-2.8.4/bin/bsdcpio.exe" "-r" "C:/dev/igrep/packages/libarchive-2.8.4/cpio/test" "test_option_J_upper")
ADD_TEST(bsdcpio_test_option_L_upper "C:/dev/igrep/packages/libarchive-2.8.4/bin/bsdcpio_test.exe" "-vv" "-p" "C:/dev/igrep/packages/libarchive-2.8.4/bin/bsdcpio.exe" "-r" "C:/dev/igrep/packages/libarchive-2.8.4/cpio/test" "test_option_L_upper")
ADD_TEST(bsdcpio_test_option_Z_upper "C:/dev/igrep/packages/libarchive-2.8.4/bin/bsdcpio_test.exe" "-vv" "-p" "C:/dev/igrep/packages/libarchive-2.8.4/bin/bsdcpio.exe" "-r" "C:/dev/igrep/packages/libarchive-2.8.4/cpio/test" "test_option_Z_upper")
ADD_TEST(bsdcpio_test_option_a "C:/dev/igrep/packages/libarchive-2.8.4/bin/bsdcpio_test.exe" "-vv" "-p" "C:/dev/igrep/packages/libarchive-2.8.4/bin/bsdcpio.exe" "-r" "C:/dev/igrep/packages/libarchive-2.8.4/cpio/test" "test_option_a")
ADD_TEST(bsdcpio_test_option_c "C:/dev/igrep/packages/libarchive-2.8.4/bin/bsdcpio_test.exe" "-vv" "-p" "C:/dev/igrep/packages/libarchive-2.8.4/bin/bsdcpio.exe" "-r" "C:/dev/igrep/packages/libarchive-2.8.4/cpio/test" "test_option_c")
ADD_TEST(bsdcpio_test_option_d "C:/dev/igrep/packages/libarchive-2.8.4/bin/bsdcpio_test.exe" "-vv" "-p" "C:/dev/igrep/packages/libarchive-2.8.4/bin/bsdcpio.exe" "-r" "C:/dev/igrep/packages/libarchive-2.8.4/cpio/test" "test_option_d")
ADD_TEST(bsdcpio_test_option_f "C:/dev/igrep/packages/libarchive-2.8.4/bin/bsdcpio_test.exe" "-vv" "-p" "C:/dev/igrep/packages/libarchive-2.8.4/bin/bsdcpio.exe" "-r" "C:/dev/igrep/packages/libarchive-2.8.4/cpio/test" "test_option_f")
ADD_TEST(bsdcpio_test_option_help "C:/dev/igrep/packages/libarchive-2.8.4/bin/bsdcpio_test.exe" "-vv" "-p" "C:/dev/igrep/packages/libarchive-2.8.4/bin/bsdcpio.exe" "-r" "C:/dev/igrep/packages/libarchive-2.8.4/cpio/test" "test_option_help")
ADD_TEST(bsdcpio_test_option_l "C:/dev/igrep/packages/libarchive-2.8.4/bin/bsdcpio_test.exe" "-vv" "-p" "C:/dev/igrep/packages/libarchive-2.8.4/bin/bsdcpio.exe" "-r" "C:/dev/igrep/packages/libarchive-2.8.4/cpio/test" "test_option_l")
ADD_TEST(bsdcpio_test_option_lzma "C:/dev/igrep/packages/libarchive-2.8.4/bin/bsdcpio_test.exe" "-vv" "-p" "C:/dev/igrep/packages/libarchive-2.8.4/bin/bsdcpio.exe" "-r" "C:/dev/igrep/packages/libarchive-2.8.4/cpio/test" "test_option_lzma")
ADD_TEST(bsdcpio_test_option_m "C:/dev/igrep/packages/libarchive-2.8.4/bin/bsdcpio_test.exe" "-vv" "-p" "C:/dev/igrep/packages/libarchive-2.8.4/bin/bsdcpio.exe" "-r" "C:/dev/igrep/packages/libarchive-2.8.4/cpio/test" "test_option_m")
ADD_TEST(bsdcpio_test_option_t "C:/dev/igrep/packages/libarchive-2.8.4/bin/bsdcpio_test.exe" "-vv" "-p" "C:/dev/igrep/packages/libarchive-2.8.4/bin/bsdcpio.exe" "-r" "C:/dev/igrep/packages/libarchive-2.8.4/cpio/test" "test_option_t")
ADD_TEST(bsdcpio_test_option_u "C:/dev/igrep/packages/libarchive-2.8.4/bin/bsdcpio_test.exe" "-vv" "-p" "C:/dev/igrep/packages/libarchive-2.8.4/bin/bsdcpio.exe" "-r" "C:/dev/igrep/packages/libarchive-2.8.4/cpio/test" "test_option_u")
ADD_TEST(bsdcpio_test_option_version "C:/dev/igrep/packages/libarchive-2.8.4/bin/bsdcpio_test.exe" "-vv" "-p" "C:/dev/igrep/packages/libarchive-2.8.4/bin/bsdcpio.exe" "-r" "C:/dev/igrep/packages/libarchive-2.8.4/cpio/test" "test_option_version")
ADD_TEST(bsdcpio_test_option_y "C:/dev/igrep/packages/libarchive-2.8.4/bin/bsdcpio_test.exe" "-vv" "-p" "C:/dev/igrep/packages/libarchive-2.8.4/bin/bsdcpio.exe" "-r" "C:/dev/igrep/packages/libarchive-2.8.4/cpio/test" "test_option_y")
ADD_TEST(bsdcpio_test_option_z "C:/dev/igrep/packages/libarchive-2.8.4/bin/bsdcpio_test.exe" "-vv" "-p" "C:/dev/igrep/packages/libarchive-2.8.4/bin/bsdcpio.exe" "-r" "C:/dev/igrep/packages/libarchive-2.8.4/cpio/test" "test_option_z")
ADD_TEST(bsdcpio_test_owner_parse "C:/dev/igrep/packages/libarchive-2.8.4/bin/bsdcpio_test.exe" "-vv" "-p" "C:/dev/igrep/packages/libarchive-2.8.4/bin/bsdcpio.exe" "-r" "C:/dev/igrep/packages/libarchive-2.8.4/cpio/test" "test_owner_parse")
ADD_TEST(bsdcpio_test_passthrough_dotdot "C:/dev/igrep/packages/libarchive-2.8.4/bin/bsdcpio_test.exe" "-vv" "-p" "C:/dev/igrep/packages/libarchive-2.8.4/bin/bsdcpio.exe" "-r" "C:/dev/igrep/packages/libarchive-2.8.4/cpio/test" "test_passthrough_dotdot")
ADD_TEST(bsdcpio_test_passthrough_reverse "C:/dev/igrep/packages/libarchive-2.8.4/bin/bsdcpio_test.exe" "-vv" "-p" "C:/dev/igrep/packages/libarchive-2.8.4/bin/bsdcpio.exe" "-r" "C:/dev/igrep/packages/libarchive-2.8.4/cpio/test" "test_passthrough_reverse")
ADD_TEST(bsdcpio_test_pathmatch "C:/dev/igrep/packages/libarchive-2.8.4/bin/bsdcpio_test.exe" "-vv" "-p" "C:/dev/igrep/packages/libarchive-2.8.4/bin/bsdcpio.exe" "-r" "C:/dev/igrep/packages/libarchive-2.8.4/cpio/test" "test_pathmatch")
